---

- hosts: all
  become: true
  tasks:

  - name: remove apache2 and php package with repo index update
    apt: 
      name: 
        - apache2
        - libapache2-mod-php  
      state: absent 
      update_cache: yes
    when: ansible_distribution == "Ubuntu"   
      
  - name: remove httpd and php package with repo index update
    dnf:
      name: 
        - httpd
        - php
      state: absent
      update_cache: yes    
    when: ansible_distribution == "CentOS"    
