- name: install apache and php package
  tags: apache,httpd,php
  package: 
    name: 
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  
- name: start httpd (CentOS)
  tags: apache,httpd
  service: 
    name: "{{ apache_service }}"
    state: started
    enabled: yes
   
- name: change emain address for admin 
  tags: centos,apache,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "CentOS"  
  notify: restart_apache

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
