- name: install apache2 and php package (Ubuntu)
  tags: apache,apache2,ubuntu
  apt: 
    name: 
      - apache2
      - libapache2-mod-php  
    state: latest
  when: ansible_distribution == "Ubuntu"   

- name: install httpd and php package (CentOS)
  tags: apache,centos,httpd
  dnf:
    name: 
      - httpd
      - php  
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"
  
- name: start httpd (CentOS)
  tags: apache,centos,httpd
  service: 
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"  
   
- name: change emain address for admin 
  tags: centos,apache,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "CentOS"
  register: httpd

- name: restart httpd (CentOS)
  tags: centos,apache,httpd
  service: 
    name: httpd
    state: restarted
  when: httpd.changed    

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
